version: "3.8"

services:    
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rails-drinkTable-prod
    environment: 
      RAILS_ENV: production
      RACK_ENV: production
    env_file:
      - .env
    command: > 
      bash -c "rm -f tmp/pids/server.pid 
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000